name: Market Hours Heatmap JSON Update

# 显式开启写权限
permissions:
  contents: write
  
on:
  schedule:
    # 每天 UTC 1:00 触发（北京时间 9:00）
   # - cron: '*/10 13-21 * * 1-5'  # UTC 13:00–21:59，每 20 分钟一次，包含 20:00–21:00 时段
        # 13:30, 13:40, 13:50
    - cron: '25,40,50 13 * * 1-5'
        # 每 10 分钟一次：14:00–20:50
    - cron: '*/15 14-20 * * 1-5'
        # 21:00
    - cron: '0 21 * * 1-5'
  workflow_dispatch:  # 手动也能触发

jobs:
  gen-and-commit:
    runs-on: ubuntu-latest

    steps:
    # —— 在这里打印 UTC 时间 ——  
    - name: Print UTC time
      run: |
        date --utc

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 允许后续步骤推送回同一 repo
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests yfinance

    - name: Generate heatmap JSON
      working-directory: StockMap
      run: |
        python -u create_realtime-heapmap-json.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add StockMap/public/data/{*_heatmap.json,3index_realtime_*.json}
        # 如果有其它输出目录，也一并 add
        # git add public/data/*.json
        # 只在有变动时才提交
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: realtime heatmap update [skip ci]"
          git push
        fi
